ProductDetailsScreen As screen:
    Fill: =RGBA(255, 255, 255, 1)
    Height: =Max(App.Height, App.DesignHeight)
    Width: =Max(App.Width, App.DesignWidth)

    Group4 As group:
        Height: =100
        Width: =100
        X: =0
        Y: =0
        ZIndex: =1

        Rectangle1_9 As rectangle:
            BorderColor: =RGBA(0, 0, 255, 1)
            DisabledFill: =Rectangle1_9.Fill
            Fill: =RGBA(49,61,75,1)
            HoverFill: =Rectangle1_9.Fill
            OnSelect: =Navigate(HomeScreen,ScreenTransition.Fade)
            PressedFill: =Rectangle1_9.Fill
            TabIndex: =0
            Width: =100
            ZIndex: =21

        icon2 As icon.ChevronLeft:
            BorderColor: =RGBA(0, 0, 0, 1)
            Color: =RGBA(255, 255, 255, 1)
            DisabledBorderColor: =RGBA(56, 56, 56, 1)
            DisabledFill: =icon2.Fill
            Height: =37
            HoverBorderColor: =ColorFade(icon2.BorderColor, 20%)
            HoverColor: =ColorFade(icon2.Color, 20%)
            HoverFill: =icon2.Fill
            Icon: =Icon.ChevronLeft
            OnSelect: =Navigate(HomeScreen,ScreenTransition.Fade)
            PressedBorderColor: =ColorFade(icon2.BorderColor, -20%)
            PressedColor: =ColorFade(icon2.Color, -20%)
            PressedFill: =icon2.Fill
            TabIndex: =0
            Width: =37
            X: =30
            Y: =31.5
            ZIndex: =22

    Rectangle3_2 As rectangle:
        BorderColor: =RGBA(0, 0, 255, 1)
        DisabledFill: =Rectangle3_2.Fill
        Fill: =RGBA(211,52,52,1)
        Height: =30
        HoverFill: =Rectangle3_2.Fill
        PressedFill: =Rectangle3_2.Fill
        TabIndex: =0
        Visible: =First(ProductRecord).DefaultSellingQuantity=0
        Width: =136
        X: =40
        Y: =318.5
        ZIndex: =2

    Rectangle1_8 As rectangle:
        BorderColor: =RGBA(153, 153, 153, 1)
        BorderThickness: =2
        DisabledFill: =Rectangle1_8.Fill
        Fill: =RGBA(240,240,240,1)
        Height: =110.96002197265625
        HoverFill: =Rectangle1_8.Fill
        PressedFill: =Rectangle1_8.Fill
        TabIndex: =0
        Width: =452
        X: =37
        Y: =416
        ZIndex: =3

    Rectangle1_6 As rectangle:
        BorderColor: =RGBA(0, 0, 255, 1)
        DisabledFill: =Rectangle1_6.Fill
        Fill: =RGBA(49,61,75,1)
        HoverFill: =Rectangle1_6.Fill
        PressedFill: =Rectangle1_6.Fill
        TabIndex: =0
        Width: =1024
        ZIndex: =4

    Rectangle1_7 As rectangle:
        BorderColor: =RGBA(0, 0, 255, 1)
        DisabledFill: =Rectangle1_7.Fill
        Fill: =RGBA(240,240,240,1)
        Height: =178
        HoverFill: =Rectangle1_7.Fill
        PressedFill: =Rectangle1_7.Fill
        TabIndex: =0
        Width: =1024
        Y: =100
        ZIndex: =5

    ProductNameText As label:
        Align: =TextPosition.Left
        BorderColor: =RGBA(0, 0, 0, 1)
        Color: =RGBA(49, 61, 75, 1)
        Font: =Font.Lato
        HoverBorderColor: =ProductNameText.BorderColor
        HoverColor: =ProductNameText.Color
        HoverFill: =ProductNameText.Fill
        PressedBorderColor: =ProductNameText.BorderColor
        PressedColor: =ProductNameText.Color
        PressedFill: =ProductNameText.Fill
        Size: =25
        Text: =First(ProductRecord).ProductName
        Width: =777
        X: =204
        Y: =120
        ZIndex: =6

    TextBox1_20 As label:
        Align: =TextPosition.Left
        BorderColor: =RGBA(0, 0, 0, 1)
        Color: =RGBA(128, 128, 128, 1)
        Font: =Font.Lato
        HoverBorderColor: =TextBox1_20.BorderColor
        HoverColor: =TextBox1_20.Color
        HoverFill: =TextBox1_20.Fill
        PressedBorderColor: =TextBox1_20.BorderColor
        PressedColor: =TextBox1_20.Color
        PressedFill: =TextBox1_20.Fill
        Size: =16
        Text: ="Current stock"
        Width: =199
        X: =62
        Y: =477
        ZIndex: =7

    Image1_9 As image:
        ApplyEXIFOrientation: =false
        BorderColor: =RGBA(0, 0, 0, 1)
        Height: =176
        HoverBorderColor: =ColorFade(Image1_9.BorderColor, 20%)
        HoverFill: =ColorFade(Image1_9.Fill, 20%)
        Image: ='Property Image'
        ImagePosition: =ImagePosition.Fill
        PressedBorderColor: =ColorFade(Image1_9.BorderColor, -20%)
        PressedFill: =ColorFade(Image1_9.Fill, -20%)
        TabIndex: =0
        Width: =176
        Y: =100
        ZIndex: =8

    TextBox1_21 As label:
        Align: =TextPosition.Left
        BorderColor: =RGBA(0, 0, 0, 1)
        Color: =RGBA(49, 61, 75, 1)
        Font: =Font.Lato
        FontWeight: =FontWeight.Semibold
        HoverBorderColor: =TextBox1_21.BorderColor
        HoverColor: =TextBox1_21.Color
        HoverFill: =TextBox1_21.Fill
        PressedBorderColor: =TextBox1_21.BorderColor
        PressedColor: =TextBox1_21.Color
        PressedFill: =TextBox1_21.Fill
        Size: =25
        Text: =First(ProductRecord).SELLINGUNITPRICECURRENCY_CURRENCYCODE & " " &First(ProductRecord).SellingUnitPrice&"/unit"
        Width: =599
        X: =204
        Y: =164
        ZIndex: =9

    DescriptionText As label:
        Align: =TextPosition.Left
        BorderColor: =RGBA(0, 0, 0, 1)
        Color: =RGBA(128, 128, 128, 1)
        Font: =Font.Lato
        HoverBorderColor: =DescriptionText.BorderColor
        HoverColor: =DescriptionText.Color
        HoverFill: =DescriptionText.Fill
        PressedBorderColor: =DescriptionText.BorderColor
        PressedColor: =DescriptionText.Color
        PressedFill: =DescriptionText.Fill
        Size: =20
        Text: =First(ProductRecord).Description
        Width: =777
        X: =204
        Y: =218
        ZIndex: =10

    outofstock As label:
        Align: =LayoutAlignItems.Center
        BorderColor: =RGBA(0, 0, 0, 1)
        Color: =RGBA(255, 255, 255, 1)
        Font: =Font.'Lato Light'
        FontWeight: =FontWeight.Semibold
        Height: =31
        HoverBorderColor: =outofstock.BorderColor
        HoverColor: =outofstock.Color
        HoverFill: =outofstock.Fill
        PressedBorderColor: =outofstock.BorderColor
        PressedColor: =outofstock.Color
        PressedFill: =outofstock.Fill
        Text: ="Out of Stock"
        Visible: =First(ProductRecord).DefaultSellingQuantity=0
        Width: =136
        X: =40
        Y: =320
        ZIndex: =11

    TextBox1_23 As label:
        Align: =TextPosition.Left
        BorderColor: =RGBA(0, 0, 0, 1)
        Color: =RGBA(49, 61, 75, 1)
        Font: =Font.Lato
        HoverBorderColor: =TextBox1_23.BorderColor
        HoverColor: =TextBox1_23.Color
        HoverFill: =TextBox1_23.Fill
        PressedBorderColor: =TextBox1_23.BorderColor
        PressedColor: =TextBox1_23.Color
        PressedFill: =TextBox1_23.Fill
        Size: =23
        Text: ="Inventory level"
        Width: =382
        X: =29
        Y: =366
        ZIndex: =12

    CurrentStock As label:
        Align: =TextPosition.Left
        BorderColor: =RGBA(0, 0, 0, 1)
        Color: =RGBA(49, 61, 75, 1)
        Font: =Font.Lato
        HoverBorderColor: =CurrentStock.BorderColor
        HoverColor: =CurrentStock.Color
        HoverFill: =CurrentStock.Fill
        PressedBorderColor: =CurrentStock.BorderColor
        PressedColor: =CurrentStock.Color
        PressedFill: =CurrentStock.Fill
        Size: =30
        Text: =First(ProductRecord).DefaultSellingQuantity
        Width: =185
        X: =61
        Y: =436
        ZIndex: =13

    TextBox1_25 As label:
        Align: =TextPosition.Left
        BorderColor: =RGBA(0, 0, 0, 1)
        Color: =RGBA(128, 128, 128, 1)
        Font: =Font.Lato
        HoverBorderColor: =TextBox1_25.BorderColor
        HoverColor: =TextBox1_25.Color
        HoverFill: =TextBox1_25.Fill
        PressedBorderColor: =TextBox1_25.BorderColor
        PressedColor: =TextBox1_25.Color
        PressedFill: =TextBox1_25.Fill
        Size: =16
        Text: ="Ideal stock"
        Width: =199
        X: =285
        Y: =477
        ZIndex: =14

    IdealStock As label:
        Align: =TextPosition.Left
        BorderColor: =RGBA(0, 0, 0, 1)
        Color: =RGBA(49, 61, 75, 1)
        Font: =Font.Lato
        HoverBorderColor: =IdealStock.BorderColor
        HoverColor: =IdealStock.Color
        HoverFill: =IdealStock.Fill
        PressedBorderColor: =IdealStock.BorderColor
        PressedColor: =IdealStock.Color
        PressedFill: =IdealStock.Fill
        Size: =30
        Text: =LookUp(Products,ProductNumber=First(ProductRecord).ProductNumber,Stock)
        Width: =186
        X: =285
        Y: =436
        ZIndex: =15

    TextBox1_27 As label:
        Align: =TextPosition.Left
        BorderColor: =RGBA(0, 0, 0, 1)
        Color: =RGBA(49, 61, 75, 1)
        Font: =Font.Lato
        HoverBorderColor: =TextBox1_27.BorderColor
        HoverColor: =TextBox1_27.Color
        HoverFill: =TextBox1_27.Fill
        PressedBorderColor: =TextBox1_27.BorderColor
        PressedColor: =TextBox1_27.Color
        PressedFill: =TextBox1_27.Fill
        Size: =23
        Text: ="Order quantity"
        Visible: =If(Value(IdealStock.Text-CurrentStock.Text)<=0,false,true)
        Width: =382
        X: =530
        Y: =366
        ZIndex: =16

    OrderQuantityText As text:
        BorderColor: =RGBA(62,142,198,1)
        BorderThickness: =1
        Color: =RGBA(49, 61, 75, 1)
        Default: =Value(IdealStock.Text-CurrentStock.Text)
        DisplayMode: =If(false,DisplayMode.View,DisplayMode.Edit)
        Fill: =RGBA(0, 0, 0, 0)
        FocusedBorderThickness: =3
        Font: =Font.Lato
        Height: =80.051504516602
        HintText: =""
        HoverFill: =ColorFade(RGBA(190, 202, 226, 0), 0%)
        PaddingLeft: =35
        PressedBorderColor: =OrderQuantityText.HoverBorderColor
        PressedColor: =OrderQuantityText.Color
        PressedFill: =OrderQuantityText.Fill
        RadiusBottomLeft: =80
        RadiusBottomRight: =80
        RadiusTopLeft: =80
        RadiusTopRight: =80
        Size: =30
        Visible: =If(Value(IdealStock.Text-CurrentStock.Text)<=0,false,true)
        Width: =454.340087890625
        X: =536
        Y: =431
        ZIndex: =17

    TextBox1_28 As label:
        Align: =TextPosition.Right
        BorderColor: =RGBA(0, 0, 0, 1)
        Color: =RGBA(49, 61, 75, 1)
        Font: =Font.Lato
        HoverBorderColor: =TextBox1_28.BorderColor
        HoverColor: =TextBox1_28.Color
        HoverFill: =TextBox1_28.Fill
        PressedBorderColor: =TextBox1_28.BorderColor
        PressedColor: =TextBox1_28.Color
        PressedFill: =TextBox1_28.Fill
        Size: =23
        Text: ="Total"
        Visible: =If(Value(IdealStock.Text-CurrentStock.Text)<=0,false,true)
        Width: =229
        X: =234.8051948051948
        Y: =569.5
        ZIndex: =19

    TotalAmountText As label:
        Align: =TextPosition.Left
        BorderColor: =RGBA(0, 0, 0, 1)
        Color: =RGBA(49, 61, 75, 1)
        Font: =Font.Lato
        FontWeight: =FontWeight.Semibold
        Height: =89
        HoverBorderColor: =TotalAmountText.BorderColor
        HoverColor: =TotalAmountText.Color
        HoverFill: =TotalAmountText.Fill
        PressedBorderColor: =TotalAmountText.BorderColor
        PressedColor: =TotalAmountText.Color
        PressedFill: =TotalAmountText.Fill
        Size: =40
        Text: =Value(OrderQuantityText.Text)*First(ProductRecord).SellingUnitPrice & " " & First(ProductRecord).SELLINGUNITPRICECURRENCY_CURRENCYCODE
        Visible: =If(Value(IdealStock.Text-CurrentStock.Text)<=0,false,true)
        Width: =507.194805194805
        X: =482.8051948051948
        Y: =545
        ZIndex: =20

    Button1_1 As button:
        BorderColor: =RGBA(62,142,198,1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledBorderColor: =ColorFade(Button1_1.BorderColor, 70%)
        DisplayMode: =If(If(Value(OrderQuantityText.Text) <=0,true,false),DisplayMode.Disabled,false,DisplayMode.View,DisplayMode.Edit)
        Fill: =RGBA(62,142,198,1)
        Font: =Font.Lato
        FontWeight: =FontWeight.Normal
        Height: =80
        HoverBorderColor: =ColorFade(Button1_1.BorderColor, 20%)
        HoverColor: =Button1_1.Color
        HoverFill: =ColorFade(Button1_1.Fill, 20%)
        OnSelect: |-
            =Patch(Products,LookUp(Products,ProductNumber=First(ProductRecord).ProductNumber),{DefaultSellingQuantity:Value(OrderQuantityText.Text+CurrentStock.Text)});Navigate(ConfirmationScreen,ScreenTransition.Fade)
        PressedBorderColor: =Button1_1.Fill
        PressedColor: =Button1_1.Fill
        PressedFill: =Button1_1.Color
        RadiusBottomLeft: =80
        RadiusBottomRight: =80
        RadiusTopLeft: =80
        RadiusTopRight: =80
        Size: =20
        Text: ="Restock"
        Width: =500
        X: =262
        Y: =649
        ZIndex: =23

    TextBox1_16 As label:
        BorderColor: =RGBA(0, 0, 0, 1)
        Color: =RGBA(255, 255, 255, 1)
        Font: =Font.Lato
        HoverBorderColor: =TextBox1_16.BorderColor
        HoverColor: =TextBox1_16.Color
        HoverFill: =TextBox1_16.Fill
        PressedBorderColor: =TextBox1_16.BorderColor
        PressedColor: =TextBox1_16.Color
        PressedFill: =TextBox1_16.Fill
        Size: =22
        Text: ="Product details"
        Width: =363
        X: =91
        Y: =30
        ZIndex: =24

    Rectangle3_3 As rectangle:
        BorderColor: =RGBA(0, 0, 255, 1)
        DisabledFill: =Rectangle3_3.Fill
        Fill: =RGBA(134, 133, 134, 1)
        Height: =30
        HoverFill: =Rectangle3_3.Fill
        PressedFill: =Rectangle3_3.Fill
        TabIndex: =0
        Visible: =If((First(ProductRecord).DefaultSellingQuantity)/Value(LookUp(Products,ProductNumber=First(ProductRecord).ProductNumber,Stock))*100>=31&&(First(ProductRecord).DefaultSellingQuantity)/Value(LookUp(Products,ProductNumber=First(ProductRecord).ProductNumber,Stock))*100<=70,true,false)
        Width: =136
        X: =40
        Y: =320
        ZIndex: =25

    AverageText As label:
        Align: =LayoutAlignItems.Center
        BorderColor: =RGBA(0, 0, 0, 1)
        Color: =RGBA(255, 255, 255, 1)
        Font: =Font.'Lato Light'
        FontWeight: =FontWeight.Semibold
        Height: =30
        HoverBorderColor: =AverageText.BorderColor
        HoverColor: =AverageText.Color
        HoverFill: =AverageText.Fill
        PressedBorderColor: =AverageText.BorderColor
        PressedColor: =AverageText.Color
        PressedFill: =AverageText.Fill
        Text: ="Average"
        Visible: =If((First(ProductRecord).DefaultSellingQuantity)/Value(LookUp(Products,ProductNumber=First(ProductRecord).ProductNumber,Stock))*100>=31&&(First(ProductRecord).DefaultSellingQuantity)/Value(LookUp(Products,ProductNumber=First(ProductRecord).ProductNumber,Stock))*100<=70,true,false)
        Width: =136
        X: =40
        Y: =320
        ZIndex: =26

    Rectangle3_4 As rectangle:
        BorderColor: =RGBA(0, 0, 255, 1)
        DisabledFill: =Rectangle3_4.Fill
        Fill: =RGBA(99, 139, 44, 1)
        Height: =30
        HoverFill: =Rectangle3_4.Fill
        PressedFill: =Rectangle3_4.Fill
        TabIndex: =0
        Visible: =If((First(ProductRecord).DefaultSellingQuantity)/Value(LookUp(Products,ProductNumber=First(ProductRecord).ProductNumber,Stock))*100>70,true,false)
        Width: =136
        X: =40
        Y: =320
        ZIndex: =27

    GoodText As label:
        Align: =LayoutAlignItems.Center
        BorderColor: =RGBA(0, 0, 0, 1)
        Color: =RGBA(255, 255, 255, 1)
        Font: =Font.'Lato Light'
        FontWeight: =FontWeight.Semibold
        Height: =30
        HoverBorderColor: =GoodText.BorderColor
        HoverColor: =GoodText.Color
        HoverFill: =GoodText.Fill
        PressedBorderColor: =GoodText.BorderColor
        PressedColor: =GoodText.Color
        PressedFill: =GoodText.Fill
        Text: ="Good"
        Visible: =If((First(ProductRecord).DefaultSellingQuantity)/Value(LookUp(Products,ProductNumber=First(ProductRecord).ProductNumber,Stock))*100>70,true,false)
        Width: =136
        X: =40
        Y: =320
        ZIndex: =28

    Rectangle3_5 As rectangle:
        BorderColor: =RGBA(0, 0, 255, 1)
        DisabledFill: =Rectangle3_5.Fill
        Fill: =RGBA(211,52,52,1)
        Height: =30
        HoverFill: =Rectangle3_5.Fill
        PressedFill: =Rectangle3_5.Fill
        TabIndex: =0
        Visible: =If((First(ProductRecord).DefaultSellingQuantity)/Value(LookUp(Products,ProductNumber=First(ProductRecord).ProductNumber,Stock))*100>=1&&(First(ProductRecord).DefaultSellingQuantity)/Value(LookUp(Products,ProductNumber=First(ProductRecord).ProductNumber,Stock))*100<=30,true,false)
        Width: =136
        X: =40
        Y: =320
        ZIndex: =29

    LowText As label:
        Align: =LayoutAlignItems.Center
        BorderColor: =RGBA(0, 0, 0, 1)
        Color: =RGBA(255, 255, 255, 1)
        Font: =Font.'Lato Light'
        FontWeight: =FontWeight.Semibold
        Height: =30
        HoverBorderColor: =LowText.BorderColor
        HoverColor: =LowText.Color
        HoverFill: =LowText.Fill
        PressedBorderColor: =LowText.BorderColor
        PressedColor: =LowText.Color
        PressedFill: =LowText.Fill
        Text: ="Low"
        Visible: =If((First(ProductRecord).DefaultSellingQuantity)/Value(LookUp(Products,ProductNumber=First(ProductRecord).ProductNumber,Stock))*100>=1&&(First(ProductRecord).DefaultSellingQuantity)/Value(LookUp(Products,ProductNumber=First(ProductRecord).ProductNumber,Stock))*100<=30,true,false)
        Width: =136
        X: =40
        Y: =320
        ZIndex: =30

